Add support for configurable audience
HarryMWinters/fastapi-oidc pull request #15
Opened 2021-08-01 05:32 UTC by BoneyAz

Hey @HarryMWinters,

Thanks for this project, it's saved me a bit of time!

Adding a pull request to enable the audience to be configured. I'm working with Okta configurable Authorization Servers and would prefer my audience claim to be the URL to my API. Having it as the clientId isn't the end of the world, but having the option to configure it will make things more flexible.

Thanks again

2021-08-01 20:22 UTC, HarryMWinters requested changes
Hey @BoneyAz,

I'm very glad you've found this small project useful. Your use case seems reasonable. 

One request, can we make the `audience` argument optional and have it default to `client_id` if unspecified? That way we preserve backward compatibility.

What do think?

And thanks for contributing!

2021-08-01 22:48 UTC, BoneyAz commented
That's reasonable, pull request updated.

2021-08-02 17:43 UTC, HarryMWinters requested changes
Thanks for the changes. Looks good. Some minor suggestions but the onlym,ajor thing I'd like to see is a test(s) for the new functionality that make sure we don't break backward compatibility in the future.

2021-08-02 17:43 UTC, HarryMWinters commented on README.md
> +    "audience": "https://yourapi.url.com/api",
```suggestion
    # Audience can be omitted in which case the aud value defaults to client_id
    "audience": "https://yourapi.url.com/api",
```

2021-08-02 17:43 UTC, HarryMWinters commented on fastapi_oidc/auth.py
> +    audience: str = None,
```suggestion
    audience: Optional[str] = None,
```

2021-08-02 17:43 UTC, HarryMWinters commented on tests/test_auth.py
Can we add a test that checks that `aud` is set to `client_id` when `audience` is not specified in the `get_auth` invocation?

2021-08-03 00:55 UTC, BoneyAz commented
Tests done and run, had to make a few minor modifications eg. losing the decode('utf-8') to get tests working

2021-08-03 03:13 UTC, HarryMWinters approved these changes
Awesome! Thanks for the tests! I'll merge and release v0.0.6 tonight.

2021-08-03 06:52 UTC, BoneyAz commented
Apologies, that appears to be a problem with my environment. The tests should now work.

2021-08-03 15:16 UTC, merged

2021-08-03 15:35 UTC, HarryMWinters commented
Released in 0.0.6 and [on pypi now](https://pypi.org/project/fastapi-oidc/).

2021-08-03 22:45 UTC, BoneyAz commented
Thanks @HarryMWinters much appreciated